version: "3.7"
services:
  service:
    environment:
      - FLASK_ENV=development
    build: .
    container_name: 'api_doit'
    restart: always
    volumes:
      - .:/app
    ports:
      - "5000:5000"